[theme]
base="dark"
primaryColor="#3498db"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"

[server]
headless = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
hideSidebarNav = false
